### ISSUE TITLE
Error when composer update --dev

### ISSUE THREAD

**Issue by fbaquero** [bstrahija/laravel-modules-example#1]
I get this error:

PHP Fatal error:  Class 'Creolab\LaravelModules\ServiceProvider' not found in "{"root"}/laravel/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php

Could you help me please?

**Comment by bstrahija** [comment]
I guess you added the service provider to the list before installing the package. To supress those Laravel errors run the update command like this:

```
composer update --no-scripts
```

**Comment by akashvarlani** [comment]
can you tell me where is the database for your example...???......means where is modules.sql file...???
